version: "3.9"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=reading_list
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://db:5432/reading_list -schemas=public -user=postgres -password=postgres -connectRetries=60 clean migrate
    volumes:
      - ./db-init-scripts:/flyway/sql
    depends_on:
      db:
        condition: service_healthy
